# vLLM 멀티모델 - 균형잡힌 메모리 할당
# 실제 테스트 기반 최적화 (RTX 5090 32GB)

services:
  # TinyLlama - 최소 필요량만 할당
  tinyllama:
    image: vllm/vllm-openai:latest
    container_name: vllm-tinyllama
    ports:
      - "8001:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: [
      "--host", "0.0.0.0",
      "--model", "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
      "--served-model-name", "tinyllama",
      "--max-model-len", "1024",        # KV cache 줄이기
      "--gpu-memory-utilization", "0.15",
      "--max-num-seqs", "32",           # 동시 처리 제한
      "--enforce-eager",
      "--dtype", "float16"              # 메모리 절약
    ]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  # Qwen - 중간 할당
  qwen:
    image: vllm/vllm-openai:latest
    container_name: vllm-qwen
    ports:
      - "8002:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: [
      "--host", "0.0.0.0",
      "--model", "Qwen/Qwen2.5-3B-Instruct",
      "--served-model-name", "qwen",
      "--max-model-len", "1536",        # 적절한 KV cache
      "--gpu-memory-utilization", "0.25",
      "--max-num-seqs", "24",           # 중간 처리량
      "--trust-remote-code",
      "--enforce-eager",
      "--dtype", "float16"
    ]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    depends_on:
      - tinyllama

  # Yi - 최대 할당 (주력 모델)
  yi:
    image: vllm/vllm-openai:latest
    container_name: vllm-yi
    ports:
      - "8003:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: [
      "--host", "0.0.0.0",
      "--model", "01-ai/Yi-6B-Chat",
      "--served-model-name", "yi",
      "--max-model-len", "2048",        # 최대 컨텍스트
      "--gpu-memory-utilization", "0.50",
      "--max-num-seqs", "16",           # 품질 우선
      "--enforce-eager",
      "--dtype", "float16"
    ]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    depends_on:
      - qwen

  # 모니터링 (선택사항)
  gpu-monitor:
    image: nvidia/dcgm-exporter:latest
    container_name: gpu-monitor
    ports:
      - "9400:9400"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

networks:
  default:
    driver: bridge