global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'

  - job_name: 'qwen-model'
    static_configs:
      - targets: ['qwen-model:8001']
    metrics_path: '/metrics'

  - job_name: 'llama-model'
    static_configs:
      - targets: ['llama-model:8002']
    metrics_path: '/metrics'

  - job_name: 'gemma-model'
    static_configs:
      - targets: ['gemma-model:8003']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']