version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-bench
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_GPU=1
      - CUDA_VISIBLE_DEVICES=0
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: serve

volumes:
  ollama_data:

networks:
  default:
    driver: bridge