version: '3.8'

services:
  # SGLang 대신 vLLM을 SGLang API 형태로 실행
  sglang-compat:
    image: vllm/vllm-openai:latest
    container_name: sglang-compat-bench
    ports:
      - "9001:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    command: [
      "--host", "0.0.0.0",
      "--model", "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
      "--served-model-name", "tinyllama-sglang",
      "--max-model-len", "512",
      "--gpu-memory-utilization", "0.10",
      "--enforce-eager",
      "--max-num-seqs", "4"
    ]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    driver: bridge